name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install black isort flake8 mypy pytest pytest-cov
      - name: Format check (isort)
        run: isort . --check-only
      - name: Format check (black)
        run: black . --check
      - name: Lint (flake8)
        run: flake8 .
      - name: Type check (mypy)
        run: mypy .
      - name: Run tests
        run: pytest --cov=adv_resolver_math
